apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gateway
  annotations:
    dev.okteto.com/generate-host: "true"
#    kubernetes.io/ingress.class: "nginx"
#    cert-manager.io/cluster-issuer: "letsencrypt"
spec:
#  tls:
#    - hosts:
#        - gateway-rsoi-finisto.cloud.okteto.net
#      secretName: letsencrypt
  ingressClassName: nginx
  rules:
#    - host: gateway-rsoi-finisto.cloud.okteto.net
#      http:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gateway
                port:
                  number: 8080