apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rental-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt"
spec:
  tls:
    - hosts:
        - rental.finarsi-rsoi.site
      secretName: letsencrypt
  rules:
    - host: rental.finarsi-rsoi.site
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rental
                port:
                  number: 8070