apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
{{/*    app-label: {{ .Values.labels.appLabel }}*/}}
    app: {{ .Values.labels.app }}
  namespace: rsoi-finisto
spec:
  replicas: 1
  selector:
    matchLabels:
{{/*      app-label: {{ .Values.labels.appLabel }}*/}}
      app: {{ .Values.labels.app }}
  template:
    metadata:
      labels:
{{/*        app-label: {{ .Values.labels.appLabel }}*/}}
        app: {{ .Values.labels.app }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: "POSTGRES_HOST"
              valueFrom:
                secretKeyRef:
                  key: postgresHost
                  name: {{ .Release.Name }}-hosts
            - name: "LIBRARY_HOST"
              valueFrom:
                secretKeyRef:
                  key: libraryHost
                  name: {{ .Release.Name }}-hosts
            - name: "RATING_HOST"
              valueFrom:
                secretKeyRef:
                  key: ratingHost
                  name: {{ .Release.Name }}-hosts
            - name: "RENTAL_HOST"
              valueFrom:
                secretKeyRef:
                  key: rentalHost
                  name: {{ .Release.Name }}-hosts
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          ports:
            - containerPort: {{ .Values.service.port }}
