version: 0.8.0
image:
  pullPolicy: Always
resources:
  requests:
    cpu: 1000m
    memory: 1Gi
  limits:
    cpu: 1000m
    memory: 1Gi
#env:
#  postgresHost: postgres
#  libraryHost: library
#  ratingHost: rating
#  rentalHost: rental