apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: {{ .Chart.Name }}
  labels:
    app-label: {{ .Values.labels.appLabel }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: plaintext
  selector:
    app-label: {{ .Values.selectorLabels.appLabel }}

