name: GitHub Classroom Workflow
on:
  push:
    branches: [ master ]

env:
  POSTGRES_HOST: ${{secrets.POSTGRES_HOST}}
  LIBRARY_HOST: ${{secrets.LIBRARY_HOST}}
  RENTAL_HOST: ${{secrets.RENTAL_HOST}}
  RATING_HOST: ${{secrets.RATING_HOST}}
jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: docker/setup-buildx-action@v2

      - name: Setup kubernetes
        run: |
          echo "${{secrets.OKTETO_KUBECONFIG}}" > okteto-kube.config
          export KUBECONFIG=./okteto-kube.config:${KUBECONFIG:-$HOME/.kube/config}
          echo "$KUBECONFIG"

      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'

      - name: Maven build packages
        run: mvn clean --batch-mode --update-snapshots verify -DskipTests

      - name: Login to DockerHUB container registry
        run: docker login --username ${{secrets.DOCKERHUB_USERNAME}} --password ${{secrets.DOCKERHUB_TOKEN}}

      - name: Build docker images
        run: |
          docker build ./gateway-library-service/ --tag ${{secrets.DOCKERHUB_USERNAME}}/gateway-service:v1.7
          docker build ./rating-service/ --tag ${{secrets.DOCKERHUB_USERNAME}}/rating-service:v1.7
          docker build ./library-service/ --tag ${{secrets.DOCKERHUB_USERNAME}}/library-service:v1.7
          docker build ./reservation-service/ --tag ${{secrets.DOCKERHUB_USERNAME}}/reservation-service:v1.7

      - name: Push images to registry
        run: |
          docker push ${{secrets.DOCKERHUB_USERNAME}}/gateway-service:v1.7
          docker push ${{secrets.DOCKERHUB_USERNAME}}/rating-service:v1.7
          docker push ${{secrets.DOCKERHUB_USERNAME}}/library-service:v1.7
          docker push ${{secrets.DOCKERHUB_USERNAME}}/reservation-service:v1.7

      

      - name: Install helm chart for library system
        run: |
          helm install library-system ./k8s/libsys-chart/ --set postgresHost=$POSTGRES_HOST,libraryHost=$LIBRARY_HOST,rentalHost=$RENTAL_HOST,ratingHost=$RATING_HOST
          sleep 60    
      

      - name: Run API Tests
        uses: matt-ball/newman-action@master
        with:
          collection: v4/postman/collection.json
          environment: v4/postman/environment.json
          delayRequest: 100
          reporters: '[ "cli" ]'

      - uses: education/autograding@v1
        id: autograder
        continue-on-error: true

      - name: Github auto grader mark
        uses: Romanow/google-sheet-autograder-marker@v1.0
        with:
          google_token: ${{secrets.GOOGLE_API_KEY}}
          sheet_id: "1xkgjUX6Qmk7rdJG-QPOToav-HWWtthJjnShIKnw3oIY"
          homework_number: 5
          user_column: 'D'
          column_offset: 'F'
          mark: "'+"